# Generated by Django 5.1.3 on 2024-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('placa', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ancho', models.FloatField(verbose_name='ancho')),
                ('alto', models.FloatField(verbose_name='alto')),
                ('largo', models.FloatField(verbose_name='largo')),
            ],
        ),
    ]
