# Generated by Django 5.1.4 on 2025-01-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0005_camionerocamion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionerocamion',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR'),
        ),
    ]
