# Generated by Django 5.1.4 on 2025-01-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0006_camionerocamion_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camionerocamion',
            name='qr_code',
        ),
    ]
