# Generated by Django 5.1.4 on 2025-01-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0008_camionero_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionerocamion',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Código QR'),
        ),
    ]
