# Generated by Django 5.1.4 on 2025-01-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0011_remove_camionerocamion_qr_code_camion_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='camionerocamion',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR'),
        ),
    ]
