# Generated by Django 5.1.3 on 2024-11-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camionero',
            fields=[
                ('cedula', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('autonomo', models.BooleanField(default=True, verbose_name='Autónomo')),
            ],
        ),
    ]
