# Generated by Django 5.1.3 on 2024-11-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0002_camion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camion',
        ),
    ]
