# Generated by Django 5.1.4 on 2025-01-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0003_delete_camion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alto')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ancho')),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largo')),
            ],
        ),
        migrations.AlterField(
            model_name='camionero',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='camionero',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='camionero',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
