# Generated by Django 5.1.4 on 2025-01-12 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nose', '0004_camion_alter_camionero_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamioneroCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nose.camion', verbose_name='Camión')),
                ('camionero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nose.camionero', verbose_name='Camionero')),
            ],
            options={
                'verbose_name': 'Relación Camionero-Camión',
                'verbose_name_plural': 'Relaciones Camionero-Camión',
                'constraints': [models.UniqueConstraint(fields=('camionero', 'camion'), name='unique_camionero_camion')],
            },
        ),
    ]
